#############################################################################
# Makefile for building: an9002-qt5
# Generated by qmake (3.1) (Qt 5.15.1)
# Project:  aneng9002-qt5.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile aneng9002-qt5.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_BLUETOOTH_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=gnu++0x -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtBluetooth -I/usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = an9002-qt51.0.0
DISTDIR = /home/build/rpmbuild/BUILD/121gw-qt5/.tmp/an9002-qt51.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath-link,/usr/lib64
LIBS          = $(SUBLIBS) /usr/lib64/libQt5Svg.so /usr/lib64/libQt5Widgets.so /usr/lib64/libQt5Gui.so /usr/lib64/libQt5Bluetooth.so /usr/lib64/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		multimeter.cpp \
		display.cpp \
		packetparser.cpp qrc_assets.cpp \
		moc_mainwindow.cpp \
		moc_multimeter.cpp \
		moc_display.cpp \
		moc_packetparser.cpp
OBJECTS       = main.o \
		mainwindow.o \
		multimeter.o \
		display.o \
		packetparser.o \
		qrc_assets.o \
		moc_mainwindow.o \
		moc_multimeter.o \
		moc_display.o \
		moc_packetparser.o
DIST          = /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiAgentBase.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiContact.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiNotes.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiXml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Attica.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_ContactEditor.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_GrantleeTheme.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Gravatar.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KActivities.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KaddressbookGrantlee.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KaddressbookImportExport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KAlarmCal.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KArchive.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KAuth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCalendarCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCalUtils.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCddb.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KChart.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KContacts.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCrash.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_kdav.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KDESu.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KDEWebKit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KGantt.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KHtml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIdentityManagement.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIMAP.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KJS.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KJsEmbed.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KMailTransport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KMailTransportAkonadi.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KMime.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KontactInterface.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KParts.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KPeople.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KPIMTextEdit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KPty.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KReport3.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KrossCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KrossUi.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KRunner.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KScreen.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWallet.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Ldap.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_av.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_av_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_avwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_avwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3drender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_repparser.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webview.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Libkdepim.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Libkleo.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_MailCommon.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_MailImporter.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_MailImporterAkonadi.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Marble.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Mbox.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_MediaWiki.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_MessageComposer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_MessageCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_MessageList.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_MessageViewer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_PimCommon.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_PimCommonAkonadi.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Prison.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Qt5Keychain.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_TemplateParser.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_WebEngineViewer.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		aneng9002-qt5.pro mainwindow.h \
		multimeter.h \
		display.h \
		packetparser.h main.cpp \
		mainwindow.cpp \
		multimeter.cpp \
		display.cpp \
		packetparser.cpp
QMAKE_TARGET  = an9002-qt5
DESTDIR       = 
TARGET        = an9002-qt5


first: all
####### Build rules

an9002-qt5: ui_mainwindow.h ui_multimeter.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: aneng9002-qt5.pro /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiAgentBase.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiContact.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiNotes.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiXml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Attica.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_ContactEditor.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_GrantleeTheme.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Gravatar.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KActivities.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KaddressbookGrantlee.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KaddressbookImportExport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KAlarmCal.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KArchive.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KAuth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCalendarCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCalUtils.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCddb.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KChart.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KContacts.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCrash.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_kdav.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KDESu.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KDEWebKit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KGantt.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KHtml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIdentityManagement.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIMAP.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KJS.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KJsEmbed.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KMailTransport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KMailTransportAkonadi.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KMime.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KontactInterface.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KParts.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KPeople.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KPIMTextEdit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KPty.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KReport3.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KrossCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KrossUi.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KRunner.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KScreen.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWallet.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Ldap.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_av.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_av_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_avwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_avwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3drender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_repparser.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webview.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Libkdepim.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Libkleo.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_MailCommon.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_MailImporter.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_MailImporterAkonadi.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Marble.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Mbox.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_MediaWiki.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_MessageComposer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_MessageCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_MessageList.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_MessageViewer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_PimCommon.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_PimCommonAkonadi.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Prison.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Qt5Keychain.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_TemplateParser.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_WebEngineViewer.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		aneng9002-qt5.pro \
		assets.qrc
	$(QMAKE) -o Makefile aneng9002-qt5.pro
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_AkonadiAgentBase.pri:
/usr/lib64/qt5/mkspecs/modules/qt_AkonadiContact.pri:
/usr/lib64/qt5/mkspecs/modules/qt_AkonadiCore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_AkonadiMime.pri:
/usr/lib64/qt5/mkspecs/modules/qt_AkonadiNotes.pri:
/usr/lib64/qt5/mkspecs/modules/qt_AkonadiWidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_AkonadiXml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_Attica.pri:
/usr/lib64/qt5/mkspecs/modules/qt_Baloo.pri:
/usr/lib64/qt5/mkspecs/modules/qt_BluezQt.pri:
/usr/lib64/qt5/mkspecs/modules/qt_ContactEditor.pri:
/usr/lib64/qt5/mkspecs/modules/qt_GrantleeTheme.pri:
/usr/lib64/qt5/mkspecs/modules/qt_Gravatar.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KActivities.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KActivitiesStats.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KaddressbookGrantlee.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KaddressbookImportExport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KAlarmCal.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KArchive.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KAuth.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KAuthCore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KCalendarCore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KCalUtils.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KCddb.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KChart.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KCodecs.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KCompletion.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KContacts.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KCrash.pri:
/usr/lib64/qt5/mkspecs/modules/qt_kdav.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KDESu.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KDEWebKit.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KDNSSD.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KEmoticons.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KFileMetaData.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KGantt.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KHolidays.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KHtml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KI18n.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KIdentityManagement.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KIdleTime.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KIMAP.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KIOCore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KIOGui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_Kirigami2.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KItemModels.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KItemViews.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KJS.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KJSApi.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KJsEmbed.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KMailTransport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KMailTransportAkonadi.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KMime.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KNewStuffCore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KNotifications.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KNTLM.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KontactInterface.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KParts.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KPeople.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KPeopleWidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KPIMTextEdit.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KPlotting.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KPty.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KReport3.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KrossCore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KrossUi.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KRunner.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KScreen.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KService.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KSyntaxHighlighting.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KTextEditor.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KUnitConversion.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KWallet.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KWaylandClient.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KWaylandServer.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_Ldap.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_av.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_av_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_avwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_avwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bodymovin_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_charts_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gamepad.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_networkauth.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_pdf.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_purchasing.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3d.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3drender.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3drender_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_repparser.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scxml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webview.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webview_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_Libkdepim.pri:
/usr/lib64/qt5/mkspecs/modules/qt_Libkleo.pri:
/usr/lib64/qt5/mkspecs/modules/qt_MailCommon.pri:
/usr/lib64/qt5/mkspecs/modules/qt_MailImporter.pri:
/usr/lib64/qt5/mkspecs/modules/qt_MailImporterAkonadi.pri:
/usr/lib64/qt5/mkspecs/modules/qt_Marble.pri:
/usr/lib64/qt5/mkspecs/modules/qt_Mbox.pri:
/usr/lib64/qt5/mkspecs/modules/qt_MediaWiki.pri:
/usr/lib64/qt5/mkspecs/modules/qt_MessageComposer.pri:
/usr/lib64/qt5/mkspecs/modules/qt_MessageCore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_MessageList.pri:
/usr/lib64/qt5/mkspecs/modules/qt_MessageViewer.pri:
/usr/lib64/qt5/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib64/qt5/mkspecs/modules/qt_PimCommon.pri:
/usr/lib64/qt5/mkspecs/modules/qt_PimCommonAkonadi.pri:
/usr/lib64/qt5/mkspecs/modules/qt_Prison.pri:
/usr/lib64/qt5/mkspecs/modules/qt_Qt5Keychain.pri:
/usr/lib64/qt5/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib64/qt5/mkspecs/modules/qt_Solid.pri:
/usr/lib64/qt5/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib64/qt5/mkspecs/modules/qt_TemplateParser.pri:
/usr/lib64/qt5/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib64/qt5/mkspecs/modules/qt_WebEngineViewer.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/toolchain.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/qt.prf:
/usr/lib64/qt5/mkspecs/features/resources_functions.prf:
/usr/lib64/qt5/mkspecs/features/resources.prf:
/usr/lib64/qt5/mkspecs/features/moc.prf:
/usr/lib64/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt5/mkspecs/features/uic.prf:
/usr/lib64/qt5/mkspecs/features/unix/thread.prf:
/usr/lib64/qt5/mkspecs/features/qmake_use.prf:
/usr/lib64/qt5/mkspecs/features/file_copies.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
aneng9002-qt5.pro:
assets.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile aneng9002-qt5.pro

qmake_all: FORCE


all: Makefile an9002-qt5

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents assets.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib64/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h multimeter.h display.h packetparser.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp multimeter.cpp display.cpp packetparser.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui multimeter.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_assets.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_assets.cpp
qrc_assets.cpp: assets.qrc \
		/usr/lib64/qt5/bin/rcc \
		assets/9002-lcd.svg \
		assets/121gw-lcd.svg
	/usr/lib64/qt5/bin/rcc -name assets assets.qrc -o qrc_assets.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=gnu++0x -g -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_multimeter.cpp moc_display.cpp moc_packetparser.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_multimeter.cpp moc_display.cpp moc_packetparser.cpp
moc_mainwindow.cpp: mainwindow.h \
		multimeter.h \
		display.h \
		packetparser.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/build/rpmbuild/BUILD/121gw-qt5/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/build/rpmbuild/BUILD/121gw-qt5 -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtBluetooth -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-blackPanther-linux-gnu -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-blackPanther-linux-gnu/10/include -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_multimeter.cpp: multimeter.h \
		display.h \
		packetparser.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/build/rpmbuild/BUILD/121gw-qt5/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/build/rpmbuild/BUILD/121gw-qt5 -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtBluetooth -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-blackPanther-linux-gnu -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-blackPanther-linux-gnu/10/include -I/usr/include multimeter.h -o moc_multimeter.cpp

moc_display.cpp: display.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/build/rpmbuild/BUILD/121gw-qt5/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/build/rpmbuild/BUILD/121gw-qt5 -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtBluetooth -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-blackPanther-linux-gnu -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-blackPanther-linux-gnu/10/include -I/usr/include display.h -o moc_display.cpp

moc_packetparser.cpp: packetparser.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/build/rpmbuild/BUILD/121gw-qt5/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/build/rpmbuild/BUILD/121gw-qt5 -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtBluetooth -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-blackPanther-linux-gnu -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-blackPanther-linux-gnu/10/include -I/usr/include packetparser.h -o moc_packetparser.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_multimeter.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_multimeter.h
ui_mainwindow.h: mainwindow.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_multimeter.h: multimeter.ui \
		/usr/lib64/qt5/bin/uic \
		display.h
	/usr/lib64/qt5/bin/uic multimeter.ui -o ui_multimeter.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		multimeter.h \
		display.h \
		packetparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		multimeter.h \
		display.h \
		packetparser.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

multimeter.o: multimeter.cpp multimeter.h \
		display.h \
		packetparser.h \
		ui_multimeter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o multimeter.o multimeter.cpp

display.o: display.cpp display.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o display.o display.cpp

packetparser.o: packetparser.cpp packetparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o packetparser.o packetparser.cpp

qrc_assets.o: qrc_assets.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_assets.o qrc_assets.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_multimeter.o: moc_multimeter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_multimeter.o moc_multimeter.cpp

moc_display.o: moc_display.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_display.o moc_display.cpp

moc_packetparser.o: moc_packetparser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_packetparser.o moc_packetparser.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

